name: "TypeScript"

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  type-check:
    name: Typescript
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript Check
        run: |
          mkdir -p logs
          pnpm --filter packages/idb-cache typescript:check > logs/typescript-errors.log 2>&1 || true

      - name: Upload TypeScript Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: typescript-errors
          path: logs/typescript-errors.log
